version: "3.9"
services:
  mysql:
    image: mysql
    volumes:
      - db-mysql-ecomm:/var/lib/mysql
    container_name: mysql-ecomm
    restart: always
    ports:
      - 3307:3307
    environment:
      MYSQL_ROOT_PASSWORD: secret

  product:
    build: ./product
    container_name: ecomm-product
    ports:
     - 3001:3001
  
  account:
    build: ./account
    container_name: ecomm-account
    ports:
     - 3002:3002

  finance:
    build: ./finance
    container_name: ecomm-finance
    depends_on:
      - mysql
    ports:
     - 3003:3003

  finance-mongo:
    build: ./finance-mongo
    container_name: ecomm-finance-mongo
    ports:
      - 3005:3005

  order:
    build: ./order
    container_name: ecomm-order
    ports:
     - 3004:3004

volumes:
  db-mysql-ecomm:
