openapi: 3.0.1
info:
  description: Semana 5 - Treinamento da PagoNxt com a Alura sobre HTTP e Swagger.
  version: 0.1.0
  title: Ecomm Project
  termsOfService: http://swagger.io/terms/
  contact:
    name: Marina
    email: marina.mendes@pagonxt.com
  license:
    name: Licença
    url: http://www.alura.com
components:
  schemas:
    category:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        status:
          type: string
servers:
  - url: https://6096015d116f3f00174b29ba.mockapi.io/
    description: >-
      Server avulso que provavelmente não funciona para fazer o YML
      corretamente. Irei mudar no futuro próximo.
paths:
  /api/categories:
    get:
      tags:
        - categories
      summary: Search for all available categories
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    status:
                      type: string
        '404':
          description: Not Found
          content:
            aplication/json:
              example: Not Found
        '500':
          description: Internal Server Error
  /api/admin/categories:
    post:
      tags:
        - categories
      summary: >-
        Add a new category to the list. You need to be logged as an adminstrator
        to use this.
      responses:
        '201':
          description: Created
          content:
            aplication/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  status:
                    type: string
        '401':
          description: Unauthorized
          content:
            aplication/json:
              example: User unathorized, please check your credentials
        '500':
          description: Internal Server Error
  /api/categories/{id}:
    parameters:
      - name: id
        in: path
        description: Unique identifier
        required: true
        example: 63caa785ae701b25441ff0be
        schema:
          type: string
    get:
      tags:
        - categories
      summary: Search for category by ID
      responses:
        '200':
          description: Success
          content:
            aplication/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  status:
                    type: string
        '404':
          description: Not Found
          content:
            aplication/json:
              example: Category Not Found
        '500':
          description: Internal Server Error
  /api/admin/categories/{id}:
    parameters:
      - name: id
        in: path
        description: Unique identifier
        required: true
        example: 63caa785ae701b25441ff0be
        schema:
          type: string
    post:
      tags:
        - categories
      summary: >-
        Change category by ID. You need to be logged as an adminstrator to use
        this.
      responses:
        '202':
          description: Accepted
          content:
            aplication/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  status:
                    type: string
        '404':
          description: Not Found
          content:
            aplication/json:
              example: Category Not Found
        '500':
          description: Internal Server Error
    patch:
      tags:
        - categories
      summary: >-
        Change category status by ID. You need to be logged as an adminstrator
        to use this.
      responses:
        '202':
          description: Accepted
          content:
            aplication/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  status:
                    type: string
        '404':
          description: Not Found
          content:
            aplication/json:
              example: Category Not Found
        '500':
          description: Internal Server Error
    delete:
      tags:
        - categories
      summary: >-
        Delete category by ID. You need to be logged as an adminstrator to use
        this.
      responses:
        '200':
          description: Seccess
          content:
            aplication/json:
              example: Category deleted
        '404':
          description: Not Found
          content:
            aplication/json:
              example: Category Not Found
        '500':
          description: Internal Server Error
