openapi: 3.0.1
info:
  description: Semana 5 - Treinamento da PagoNxt com a Alura sobre HTTP e Swagger.
  version: 0.1.0
  title: Ecomm Project
  termsOfService: http://swagger.io/terms/
  contact:
    name: Marina
    email: marina.mendes@pagonxt.com
  license:
    name: Licença
    url: http://www.alura.com
components:
  schemas:
    category:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        status:
          type: string
servers:
  - url: https://6096015d116f3f00174b29ba.mockapi.io/
    description: >-
      Server avulso que provavelmente não funciona para fazer o YML
      corretamente. Irei mudar no futuro próximo.
paths:
  /api/categories:
    get:
      tags:
        - products
      summary: Busca todas as categorias
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    status:
                      type: string
        '404':
          description: Not Found
          content:
            aplication/json:
              example: Not Found
  /api/admin/categories:
    post:
      tags:
        - products
      summary: >-
        Adiciona uma nova categoria a lista. Você deve estar logado como
        administrador para funcionamento
      responses:
        '201':
          description: Created
          content:
            aplication/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  status:
                    type: string
        '401':
          description: Unauthorized
          content:
            aplication/json:
              example: User unathorized, please check your credentials
